.PHONY: all
LIST = /as/df/apple.c /we/er/aim.c /admin/usr/lnn.h
P = echo

all:
	@$(P) "LIST = $(LIST)"
	@$(P) "basename = $(basename $(LIST))"
	@$(P) "suffix = $(suffix $(LIST))"
	@$(P) "dir = $(dir $(LIST))"
	@$(P) "notdir = $(notdir $(LIST))"
	@$(P) "addsuffix = $(addsuffix .m, $(basename $(LIST)))"
	@$(P) "addprefix = $(addprefix _t,$(notdir $(LIST)))"
	@$(P) "join = $(join $(basename $(LIST)),".a .b .c")"

